- name: load kibana
  shell:
    conduct load --ip 192.168.77.20 /usr/share/conductr/extra/conductr-kibana*


- pause: seconds=5


- name: run kibana
  shell:
    conduct run --ip 192.168.77.20 conductr-kibana

