---
- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest update_cache=yes

- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 Licence
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-8-licence-acceptance

#  Using force to accept packages that cannot be authenticated!
#  libfontenc1 java-common gsfonts x11-common xfonts-encodings xfonts-utils gsfonts-x11
- name: Install Oracle Java 8
  apt: name={{item}} state=latest force=yes
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
