- name: load visualizer
  shell:
    /home/vagrant/.local/bin/conduct load --ip 192.168.77.20 /usr/share/conductr/samples/visualizer*
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"


- pause: seconds=5


- name: run visualizer
  shell:
    /home/vagrant/.local/bin/conduct run --ip 192.168.77.20 3201ad4
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

