- name: Add Proxy repo
  apt_repository: repo='ppa:vbernat/haproxy-1.5'

- name: Install haproxy
  apt: name=haproxy update_cache=yes force=yes

- name: install conductr bundle updater
  shell:
    dpkg -i /usr/share/conductr/extra/conductr-haproxy_0.1.0_all.deb


- name: Grant HAProxy configuration file read and write access to ConductR-HAProxy application
  shell:
    chown conductr-haproxy:conductr-haproxy /etc/haproxy/haproxy.cfg

#- name: Grant permissions for the particular command that ConductR-HAProxy is going to use by modifying the sudoers file
#  command:
#    echo "conductr-haproxy ALL=(root) NOPASSWD: /etc/init.d/haproxy reload" | sudo tee -a /etc/sudoers

# this hack is due to bug in ansible 1.8
- name: Grant permissions for the particular command that ConductR-HAProxy is going to use by modifying the sudoers file
  script:
    haproxy_sudoers.sh

- name: Set the ConductR IP address which is going to be used by ConductR-HAProxy to listen to bundle events in the cluster
  shell:
    echo -Dconductr-haproxy.ip={{conductr_ip}} | sudo tee -a /usr/share/conductr-haproxy/conf/application.ini

- name: restart haproxy
  shell:
    /etc/init.d/conductr-haproxy restart
