---
- name: Copy ConductR
  copy: src=conductr/files/{{ CONDUCTR_PKG }} dest=/home/vagrant

- name: Install ConductR
  apt: deb=/home/vagrant/{{ CONDUCTR_PKG }}

- name: Install Conductr-Haproxy
  apt: deb=/usr/share/conductr/extra/{{ CONDUCTR_HAPROXY_PKG }}

- command: rm /home/vagrant/{{ CONDUCTR_PKG }}

- name: Setup Python, Pip
  apt: name={{ item }} state=latest
  with_items:
    - python3-pip
    - python-dev
    - python-setuptools
  when: "{{ INSTALL_CLI }} == true"

- name: Install ConductR CLI
  command: pip3 install -U conductr-cli
  become: yes
  become_method: sudo
  when: "{{ INSTALL_CLI }} == true"


- shell: 'echo -Dconductr.ip={{ conductr_ip }} | sudo tee -a /usr/share/conductr/conf/application.ini'
  become: yes
  become_method: sudo


- shell: 'echo -DCONDUCTR_IP={{ conductr_ip }} | sudo tee -a /usr/share/conductr/conf/application.ini'
  become: yes
  become_method: sudo


- shell: 'echo export CONDUCTR_IP=$(hostname -i) | sudo tee -a /etc/profile'
  become: yes
  become_method: sudo


- shell: 'echo -Dconductr-haproxy.ip={{ conductr_ip }} | sudo tee -a /usr/share/conductr-haproxy/conf/application.ini'
  become: yes
  become_method: sudo

- command: chown conductr-haproxy:conductr-haproxy /etc/haproxy/haproxy.cfg
  become: yes
  become_method: sudo

- shell: 'echo "conductr-haproxy ALL=(root) NOPASSWD: /etc/init.d/haproxy reload" | sudo tee -a /etc/sudoers'
  become: yes
  become_method: sudo

- shell: "echo '$ModLoad imtcp' | sudo tee -a /etc/rsyslog.d/conductr.conf"
  become: yes
  become_method: sudo

- shell: "echo '$InputTCPServerRun 514' | sudo tee -a /etc/rsyslog.d/conductr.conf"
  become: yes
  become_method: sudo



- name: Set akka role
  shell:
    echo -Dakka.cluster.roles.0={{node_akka_role}} | sudo tee -a /usr/share/conductr/conf/application.ini
  become: yes
  become_method: sudo


- name: Set seed
  shell:
    echo --seed {{seed_ip}}:9004 | sudo tee -a /usr/share/conductr/conf/application.ini
  become: yes
  become_method: sudo
  when: "{{ IS_SEED }} == false"



- service: name=conductr state=restarted
- service: name=conductr-haproxy state=restarted
- service: name=rsyslog state=restarted

