# Update all packages to the latest version
- apt: update_cache=yes
  tags: [conductr-seed]

- name: Install conductr
  shell:
    dpkg -i /vagrant/{{conductr_dist}}
  tags: [conductr-seed]

- name: Set CONDUCTR_IP
  shell:
    echo -DCONDUCTR_IP={{conductr_ip}} | sudo tee -a /usr/share/conductr/conf/application.ini
  tags: [conductr-seed]

- name: Restart ConductR
  shell:
    /etc/init.d/conductr restart
  tags: [conductr-seed]




