# Update all packages to the latest version
- apt: upgrade=dist
  tags: [conductr-seed]

- name: Install conductr
  shell:
    dpkg -i /vagrant/conductr_1.0.0-b1_all.deb
  tags: [conductr-seed]

- name: Set CONDUCTR_IP
  shell:
    echo -DCONDUCTR_IP={{conductr_ip}} | sudo tee -a /etc/default/conductr
  tags: [conductr-seed]

- name: Restart ConductR
  shell:
    /etc/init.d/conductr restart
  tags: [conductr-seed]




